
app = "tailscale-vpn-wild-haze-7043"
primary_region = "nrt"
kill_signal = "SIGINT"
kill_timeout = "5s"

[env]
  PORT = "41641"
  TAILSCALE_HOSTNAME = "tailscale-vpn"

[[services]]
  protocol = "udp"
  internal_port = 41641
  processes = ["app"]

  [[services.ports]]
    port = 41641

  [services.concurrency]
    type = "connections"
    hard_limit = 100
    soft_limit = 75
