app = "tailscale-fly"
primary_region = "nrt"

[build]
  image = "ghcr.io/lilac/tailscale-fly:latest"

[env]
  TAILSCALE_AUTHKEY = "placeholder"
  TAILSCALE_HOSTNAME = "placeholder"
git add fly.toml
git commit -m "fix: replace fly.toml with correct config"
git push origin main
